### ISSUE TITLE
[WinError 2] The system cannot find the file specified - 09/17/2019

### ISSUE THREAD

**Issue by dracodragon777** [Egoistically/ALAuto#1]
https://imgur.com/a/fDREyNI
Running on Windows 10.
I'm having troubles running the app. I have included pictures of what I have done.
What am I missing? I think I have followed the steps.

**Comment by Egoistically** [comment]
Looks like adb isn't added to your path.
Here you have a link with instructions: https://www.xda-developers.com/install-adb-windows-macos-linux/.
Sorry for taking this long to respond.

**Comment by dracodragon777** [comment]
Ah thanks. Hmm does this work for emulators? I'm using BlueStacks 4 because my phone is 2.3.7v. I followed the instructions for Windows and it didn't mention adding it as a PATH. I got the started successfully and list of devices attached message. Then started it and got the WinError 2 again. What line would I have to add?

Ah it is ok. It was next day so way better than what I was expecting.

**Comment by Egoistically** [comment]
It does, I don't know how to enable adb debugging on BlueStacks but it should work.
Instructions are very basic and a lot more things need to be done, I will update them later today.
You can add me on Discord if you want ego#9459.
