### ISSUE TITLE
Loading screen is never found.

### ISSUE THREAD

**Issue by Satoshiii-DCS** [Egoistically/ALAuto#101]
Unit Model: SM-J730G

The message "Loading screen was not found but combat pause is present, assuming combat is initiated normally." Always pops up and the bot does not continue pressing the confirm button once the battle ends.

Is this regularly happening or just me?

Also, the script gets stuck at the results screen.
![Screenshot (71)](https://user-images.githubusercontent.com/61380847/76221805-9b453380-6254-11ea-86f1-354479e4e5d7.png)

It's not an emulator. It's just a screen copy script.

______________________________________________________________
Also coming from the same device, the script cannot recognize maps anymmore as it always gives the error that the map cannot be found in the world and requires manual searching.

**Comment by hjk22** [comment]
Do you still have these issues? Since your phone resolution is correct, it might be because phones generally have higher DPI than emulators: try lowering it. If it doesn't work, the other solution is to remake the assets yourself.

**Comment by Satoshiii-DCS** [comment]
Issue is gone now. Just recently tried using the bot again and it works.
