### ISSUE TITLE
Evade ambushes

### ISSUE THREAD

**Issue by Grofd98** [Egoistically/ALAuto#118]
Is it possible to let the bot handle with ambushes? At the moment the bot is stucked every time he has to manage an ambush. Am I blind and there is an option or is it impossible for now?

**Comment by UserFromSpace** [comment]
Oblivious to the existence of a wiki? 

Set "ClearingMode" to "False".

If you actually read the wiki, even once, you would've known what "ClearingMode" is. Please refer to it for more information.
