### ISSUE TITLE
connected but do nothing usefull

### ISSUE THREAD

**Issue by NodokaMurmevent** [Egoistically/ALAuto#13]
Hello i try to use the script but it not work
Nox rooted + Debug enabled
i start ADB :
```
> adb connect 127.0.0.1:62001
connected to 127.0.0.1:62001

```
i have this on config : 
```
[Network]
Service: 127.0.0.1:62001
```
and i start the script : 
```
PS C:\Users\Miaou\ALAuto> python .\ALAuto.py
[2019-10-17 18:49:35] Initializing config module
[2019-10-17 18:49:35] Validating config
[2019-10-17 18:49:35] Starting ALAuto!
* daemon not running; starting now at tcp:5037
* daemon started successfully
[2019-10-17 18:49:41] Sucessfully connected to the service.
```

aaaaand... he no thing but spam the top left corner.

i missed something ?

**Comment by KurutsuKaren** [comment]
Can you share full `config.ini`?

**Comment by Egoistically** [comment]
It's not an adb related error, it's getting stuck here for some reason:
```python
    if not Utils.find("menu/button_battle"):
        Utils.touch_randomly(Region(54, 57, 67, 67))
        Utils.script_sleep(1)
        continue
```
Do what @KurutsuKaren said, please.

**Comment by hjk22** [comment]
If it spams the top left corner, it means the script is not able to find the battle button. Have you changed your emulator resolution to the one suggested (1920x1080)? Otherwise the library used for image recognition won't work.

**Comment by NodokaMurmevent** [comment]
ok found it it's was the resolution, i changed to 1920x1080 and it's work perfectly, sorry to be a retard
