### ISSUE TITLE
Just a question, speed of auto farm.

### ISSUE THREAD

**Issue by NodokaMurmevent** [Egoistically/ALAuto#14]
the auto farming work well (but no kaga TT__TT ), thank again for this ! 

i juste have a little question, for each action it's take realy a long time, for exemple in 30min the script to only 4 complet run.

i am cursions to know, it's because a limitation (it's take time to reconize the image maybe) or a choice for avoid an ban ?

**Comment by Egoistically** [comment]
Stability > Speed, as easy as that.

**Comment by NodokaMurmevent** [comment]
Ok, thanks for the reply, i was just curious.

**Comment by Egoistically** [comment]
It's fine, if you have any further questions you can add me on Discord ego#9459.
