### ISSUE TITLE
when i set oillimit log say 0

### ISSUE THREAD

**Issue by Walofz** [Egoistically/ALAuto#19]
How to fix it ?

![image](https://user-images.githubusercontent.com/29043573/68075700-d1256780-fddd-11e9-9173-589a77333b76.png)

**Comment by Zumochi** [comment]
I'm actually having the same problem 😄
For now I just set the limit to 0.

**Comment by Walofz** [comment]
yes. this time i set 0 but i want stock oil for daliy map.

**Comment by Egoistically** [comment]
Wasn't home for the past few days, will check it out later. Sorry for the inconvenience.

**Comment by Walofz** [comment]
take care yourself bro. :)

**Comment by Egoistically** [comment]
Just like they did with fonts they decided to slightly change the oil ui.
Should be fixed https://github.com/Egoistically/ALAuto/commit/43eb8ba4fe4bfc2214faa98576430b802ef88e8e.
