### ISSUE TITLE
after end boss battle ui stuck at map screen

### ISSUE THREAD

**Issue by Walofz** [Egoistically/ALAuto#20]
![image](https://user-images.githubusercontent.com/29043573/68169223-eb0da880-ff9d-11e9-80ea-89d45bdaf660.png)

**Comment by Egoistically** [comment]
Has happened to me a few times. I don't know what could be causing it since it's very inconsistent (at least on my end).
If anyone can provide me with a video or more information I'll look into it.

**Comment by D4rkAng31** [comment]
Could have something to do with the script no longer saying "combat ended" at the end of every sortie.

**Comment by D4rkAng31** [comment]
Also, if you manually re-enter the map after the bug happens the script continues.

**Comment by Walofz** [comment]
i think problem in event script "combat ended". it's not show in this update.

in my video before end i cancel script.


https://youtu.be/wca1yGc5Veo

**Comment by Egoistically** [comment]
I'm fucking retarded for not testing updates before I push them, this should fix it https://github.com/Egoistically/ALAuto/commit/3339d633228f7d257890471b916b42555e25733b.

**Comment by Walofz** [comment]
i think is bug again but this bug "when you recieve SSR ships after end boss node" it's stuck at map screen. 

![image](https://user-images.githubusercontent.com/29043573/68630218-2d446600-0519-11ea-92dc-0ca0cf747865.png)


sorry for vedio i can't record it

**Comment by Walofz** [comment]
> Also, if you manually re-enter the map after the bug happens the script continues.

scripts run agian after re-enter map but fail to scan location because it not clicked to center screen.

**Comment by Egoistically** [comment]
Has it only happened once?

**Comment by Walofz** [comment]
i'll check it again. i'm bad luck for drop SSR ship.

**Comment by Egoistically** [comment]
Same thing should happen with Elites, the code is the same.

**Comment by Walofz** [comment]
ok i want 1 hour for check it. i think is problem only me.

**Comment by Walofz** [comment]
ok it's only problem 1 time. i close this issue.

**Comment by Walofz** [comment]
ok after test. stuck map screen when you got Elites or SSR ship in boss node. log("Combat Ended") don't show and can't go next scripts.

![image](https://user-images.githubusercontent.com/29043573/68874010-1711f200-0733-11ea-9648-486aa40687e7.png)
