### ISSUE TITLE
Slow operation, no retry after failing to find specified map

### ISSUE THREAD

**Issue by teammate165** [Egoistically/ALAuto#21]
Hi I've managed to get the bot working and noticed that it's operating speed is painfully slow (specifically scanning mob ships which takes roughly 5s), is this a hardware-based problem or is this intended speed?
I'm running i5-3550, 8GB DDR3, RX 580 4GB, Windows 10 (version 1903).

Edit 1: I noticed after 2 runs, the bot somehow goes searching for the map I specified (3-4) after having already started map clear, this is really confusing and when returning to the world map, the bot doesn't seem to try looking for the map again.
[https://imgur.com/krEuBce](url)

Edit 2: Would it be possible to make this work on smaller resolutions? This would reduce the chances of misclicks and disrupting the bot's operation, I highly doubt this is the culprit of said issue in Edit 1.

Other than that the bot works flawlessly, thank you very much for making this.

**Comment by Egoistically** [comment]
- It depends on hardware but even with a great pc searching for enemies won't take less than a few seconds.
- I don't know why that error happened, did it work fine after restarting? 
- Support for smaller resolutions would be possible but I'm absolutely not doing it, every single coordinate and asset would need to be changed and it's just not worth.

**Comment by teammate165** [comment]
About the malfunction, yes after a restart everything works normal again.

Is it possible to use an algorithm and recalculate the tap coordinates for smaller/larger resolutions (given the same aspect ratio such as 16:9)?

**Comment by Egoistically** [comment]
Yes it would be possible, would be a pain nonetheless. If anyone wants to code it I will be very thankful to them, but I'd rather focus on other stuff.

**Comment by teammate165** [comment]
Thanks for the response, I'll close this issue now.
