### ISSUE TITLE
i have question.

### ISSUE THREAD

**Issue by Walofz** [Egoistically/ALAuto#22]
`Commissions: True`
in Commission screen. you can set script disable or don't click a mission lost 1200 oil  ?

> or disable it's in **config.ini**

`Commissions: False`

i like auto commisions but sometime it's click 

> Self Training III (lost 1200 oil but i don't click it)

**Comment by Egoistically** [comment]
I don't know why it gets clicked, it has never happened to me and it's definitely not intended.

**Comment by Walofz** [comment]
in my case. when 3 fleet go mission and mission (lost 1200 oil) available. it's clicked and auto select ship full lv and go.

**Comment by Egoistically** [comment]
If you could provide a video it would help me a lot.

**Comment by Walofz** [comment]
it's hard for this time because i have 2 URGENT Mission. in that case clicked when DAILY Mission send 3 fleet and havn't URGENT Mission. in DAILY tab you script auto clicked at 4 rows because it can't scroll screen (CV2 use cap screen and check by your png right ?). my solution now is manual send mission (lost 1200 oil) and set autobot farm and select auto fleet to send mission.

**Comment by Egoistically** [comment]
Uhm... I guess I'll just rewrite the entire module later this week.

**Comment by Walofz** [comment]
first time i'll use this project to my phone but Oneplus 6T Display it display 2280 x 1080 script can't use. 

but this project is very good. it's great for farm rare ship or exp for build big ships. i think commission is option. i don't care it. thank you.

**Comment by Walofz** [comment]
in this case if commission true. it will clicked mission lost 1200 oil. because it show at 4 rows and script you set location at that point.

![Screenshot_20191108-002102](https://user-images.githubusercontent.com/29043573/68411816-c55eea00-01bd-11ea-8413-c5afb95b7d45.jpg)

**Comment by Egoistically** [comment]
Yeah but it is supposed to swipe down. I think it confuses daily with urgent tab and just goes for whatever commission sees first.

**Comment by Walofz** [comment]
it's bug or normal scripts ?

**Comment by Egoistically** [comment]
It is a bug.

**Comment by Walofz** [comment]
oh. it's really hard work. who say programmer is easy work. i'll kick ass it. i was just starting to study Python because I normally only write web applications. i think you can do it.

thank you very much. 

ps. you have link for donate ?

**Comment by Egoistically** [comment]
Soon you'll probably be better than me at python, I am such a newbie. And thank you again for being so friendly and comprehensive with me.

I don't have any link at the moment, didn't think anyone would ever want to donate.

**Comment by Walofz** [comment]
if you create donate link please share it to me. It may be a small amount of money. but i want pay for good project. this project save many my time for build Izumo.

**Comment by Egoistically** [comment]
Added a ko-fi link, hopefully works for you. And leaving the offtopic aside, I will later rewrite the commissions module to finally fix this issue.

**Comment by Walofz** [comment]
thank you very much. i'll donate in morning (this time 00:11 am)
