### ISSUE TITLE
How to speed up sorties. 

### ISSUE THREAD

**Issue by Macro-sudo** [Egoistically/ALAuto#23]
Takes me 12 mins to do one sortie on 3-4 and I'm wondering if that's normal. How long does it take you to do a sortie there and how would I be able to speed up the process? Any way to allocate more ram?
Running an i7-7500 cpu with 8 gigs of ram.

Btw, thanks for the bot :)

**Comment by Egoistically** [comment]
That's completely normal, I do on average 5 combats/hour. I could make it faster but I'd rather go for stability. After all, you can leave the bot 24 hours and the issue will end up being oil rather than speed.
