### ISSUE TITLE
can't farm event map like D3 or A1

### ISSUE THREAD

**Issue by p0ljp0p1234** [Egoistically/ALAuto#24]
I can't farm event map in divergent event

**Comment by Egoistically** [comment]
I never added them for some reason, expect an update later today.

**Comment by Egoistically** [comment]
Should be fixed if map isn't one of those extremely zoomed in or out https://github.com/Egoistically/ALAuto/commit/f5348efe2cdc9796afed863c82a0fc76425dcec2.

**Comment by p0ljp0p1234** [comment]
Thanks for the updates, I'll close this issue now.
