### ISSUE TITLE
Retreat after X fights

### ISSUE THREAD

**Issue by p0ljp0p1234** [Egoistically/ALAuto#26]
Just a thought. Because you have only 1 fleet so when you farm, sometimes you don't want your fleet to attack boss .

**Comment by Walofz** [comment]
farm with out end boss map ? why ?

**Comment by p0ljp0p1234** [comment]
like farming pr ship, you don't need to kill boss and if your pr farming fleet is weak it could be fail in boss node

**Comment by Egoistically** [comment]
Not that bad of an idea tbh, might add it.

**Comment by Egoistically** [comment]
https://github.com/Egoistically/ALAuto/commit/c39ac03c50a134310d20d80a7a57162e883d7e92
