### ISSUE TITLE
"can't find map"

### ISSUE THREAD

**Issue by D4rkAng31** [Egoistically/ALAuto#28]
![image](https://user-images.githubusercontent.com/57135409/68879737-dcb15080-0744-11ea-972d-3255e21a81f7.png)
Script enters map then says can't find map.

**Comment by D4rkAng31** [comment]
currently reverted back to an older version that doesn't have problem.

**Comment by Egoistically** [comment]
Give this a try, should be fixed https://github.com/Egoistically/ALAuto/commit/686b9e4b5a80036bff1b0227889112655a5a8543.

**Comment by D4rkAng31** [comment]
Fixed it. Thanks. Closing.
