### ISSUE TITLE
I'm stucking when I get SSR Ship.

### ISSUE THREAD

**Issue by MetalDevOps** [Egoistically/ALAuto#29]
Whenever I get an SSR ship the bot hangs and I have to restart again

![](https://i.imgur.com/lPZuTM5.png)

**Comment by Walofz** [comment]
it stucking when your end boss node and get SSR or Elite right ?

**Comment by JustShinobi** [comment]
> it stucking when your end boss node and get SSR or Elite right ?

I noticed that when the boss node is over and luckily I get an SSR ship just hangs, I just saw it happening with SSR ship

**Comment by JustShinobi** [comment]
By the way, it doesn't show any error messages, it just stops working.

**Comment by Walofz** [comment]
in my case i manual fix by

`modules\combat.py`

in line 188 - 203

            if Utils.find("menu/drop_ssr"):
                Logger.log_msg("Received SSR ship as drop.")
                Utils.touch_randomly(self.region['dismiss_ship_drop'])
                continue
            if Utils.find("menu/drop_elite"):
                Logger.log_msg("Received ELITE ship as drop.")
                Utils.touch_randomly(self.region['dismiss_ship_drop'])
                continue
            if Utils.find("menu/drop_rare"):
                Logger.log_msg("Received new RARE ship as drop.")
                Utils.touch_randomly(self.region['dismiss_ship_drop'])
                continue
            if Utils.find("menu/drop_common"):
                Logger.log_msg("Received new COMMON ship as drop.")
                Utils.touch_randomly(self.region['dismiss_ship_drop'])
                continue

just add this command before `continue`

> Utils.script_sleep(1)

simple my fix

            if Utils.find("menu/drop_ssr"):
                Logger.log_msg("Received SSR ship as drop.")
                Utils.touch_randomly(self.region['dismiss_ship_drop'])
                Utils.script_sleep(1)
                continue
            if Utils.find("menu/drop_elite"):
                Logger.log_msg("Received ELITE ship as drop.")
                Utils.touch_randomly(self.region['dismiss_ship_drop'])
                Utils.script_sleep(1)
                continue
            if Utils.find("menu/drop_rare"):
                Logger.log_msg("Received new RARE ship as drop.")
                Utils.touch_randomly(self.region['dismiss_ship_drop'])
                Utils.script_sleep(1)
                continue
            if Utils.find("menu/drop_common"):
                Logger.log_msg("Received new COMMON ship as drop.")
                Utils.touch_randomly(self.region['dismiss_ship_drop'])
                Utils.script_sleep(1)
                continue

**Comment by Walofz** [comment]
in this case when get Elite or SSR ship in boss node. scripts don't continue to show message "Combat ended". add this script for check screen again and it will find new command for go back to main screen.

**Comment by JustShinobi** [comment]
Done, I will say something if it occurs again, thanks for the tip.

**Comment by Walofz** [comment]
yep. i think him will fix it soon.

**Comment by Walofz** [comment]
result after add this scripts (Elite or SSR use same scripts)

![image](https://user-images.githubusercontent.com/29043573/69113801-a2361380-0ab6-11ea-8d98-71d92b6a37f5.png)


`modules\combat.py`

![image](https://user-images.githubusercontent.com/29043573/69113854-d9a4c000-0ab6-11ea-8329-90fc8aff3510.png)


ps. if you like this project plz donate him in tab `Sponser`

**Comment by JustShinobi** [comment]
Sure, i will buy a coffer for him soon.

**Comment by Egoistically** [comment]
It is hard for me to test such things since I barely ever get SSR drops. If your fix does indeed work I will add it into the next update.
Thank you very very much for your help.

**Comment by Walofz** [comment]
in my fix. most runing at 1 days 10 hours before i shutdown my computer via BSOD "LUL" 

it's use more luck for Elite or SSR drop in 3-4

**Comment by Egoistically** [comment]
Eyyy, glad you got her. Congrats!

**Comment by Walofz** [comment]
again. confirm my manual fix

![image](https://user-images.githubusercontent.com/29043573/69196850-45903280-0b62-11ea-9056-19b591b6c624.png)

**Comment by JustShinobi** [comment]
glad to hear that, I haven't picked up any new SSR yet to test.

Btw, I'm having several stucks on map 7, which map are you farming Walofz?

**Comment by Walofz** [comment]
i'm only farm 3-4 because **function X retire map auto not release** 

Izumo farming i use 2 BB Sakura and 1 DD (Kawakaze/Ayanami)

now. i pick new main to Ibuki, i use 1 BB (Izumo) and 2 CA/CL for farming her 

(Izuno use exp for BB,Ibuki use exp for CA/CL)

**Comment by Walofz** [comment]
i havn't time for manual farming.

in work or end work i ............

**Comment by Egoistically** [comment]
I'm using it on 6-4 and no problems so far, it always ends up idling because of oil or morale. Been playing FGO while I leave it on the background.

**Comment by Walofz** [comment]
yep,oil in azurlane has very limit,got very low oil but high for burn it. i like map oil fix form kancolle.

**Comment by Walofz** [comment]
and again bro.

![image](https://user-images.githubusercontent.com/29043573/69227113-e824d180-0bb3-11ea-9303-7caf7032f24e.png)

**Comment by Egoistically** [comment]
https://github.com/Egoistically/ALAuto/commit/bf9e45432e3d398b0d693599371fdab5846cce70
