### ISSUE TITLE
Stuck if a ship sinks and the fleet cannot be formed any more

### ISSUE THREAD

**Issue by phantasia15** [Egoistically/ALAuto#30]
If one of the ships sinks in the 1:1 composition, a message will popup saying that the fleet cannot be formed anymore and user will be force to retreat from the map. The bot will then stuck at the popup.
I took a quick look at the bot code and found out that it didn't handle the above case.
Hopefully, you can update the code to handle it.

Anyways, thanks a lot for making the bot.

**Comment by Walofz** [comment]
want more information,have picture or video ? please share it.

**Comment by phantasia15** [comment]
I couldn't reproduced the bug right now. It seemed to happen once in a while.
Also, I recheck the code and it did handle the case correctly.
I will reopen the issue when I can reproduce it.

Sorry for the trouble.
