### ISSUE TITLE
Results when closing with ^C

### ISSUE THREAD

**Issue by Zumochi** [Egoistically/ALAuto#31]
It might be nice to see the combat results you get normally after a cycle is done also when you stop the script with for example Ctrl+C.

I don't think a handler is implemented right now?

**Comment by Walofz** [comment]
Ctrl - C is ....... "Force stop scripts or command or .... if it running in this screen"

you can setting to disable key "Ctrl - C" in your terminal, and combat results. i think you can add scripts save to text file or something in ALAuto.py 

**or**
`python ALAuto.py >> log.txt`

it not show log in you terminal, if you close terminal or "Ctrl - C" in **log.txt** will have all alert result.

**Comment by Egoistically** [comment]
https://github.com/Egoistically/ALAuto/commit/358d01439507be931a0bd26ee4de17fb5eafa436 better late than never I guess.

**Comment by Zumochi** [comment]
Oh nice, thank you so much for doing the work.
