### ISSUE TITLE
mac os x/linux

### ISSUE THREAD

**Issue by jwin** [Egoistically/ALAuto#34]
Got a version of this working in mac os x, however using subprocess shell=True will fork a subshell causing the call to adb to fail.  Simply removing this flag is enough to make the rest of the script work, i can give you a pull request but i'm not sure if it'd fail windows.

**Comment by Egoistically** [comment]
I tested it and apparently makes no difference whatsoever, changed on https://github.com/Egoistically/ALAuto/commit/eaa4cdb21052a290ccef4e33f04331b56173a0bd.
