### ISSUE TITLE
No module named modules.combat

### ISSUE THREAD

**Issue by ghost** [Egoistically/ALAuto#35]
i am getting the following error.

Traceback (most recent call last):
  File "ALAuto.py", line 3, in <module>
    from modules.combat import CombatModule
ImportError: No module named modules.combat
PS D:\User\Downloads\Tools\ALAuto-master>

**Comment by Egoistically** [comment]
Did you extract everything into the same folder?

**Comment by ghost** [comment]
Yes i did except for the Config file.

**Comment by Egoistically** [comment]
![image](https://user-images.githubusercontent.com/55348950/70724840-a0e5b880-1cfb-11ea-8bcc-79eebca3708a.png)
It looks like this?

**Comment by ghost** [comment]
Yes exactly the same.

**Comment by Egoistically** [comment]
Uhhh... that's weird. I don't really understand why would it happen.

**Comment by ghost** [comment]
I fixed it, i deleted python 2.7. don't know why that was installed. I don't remember doing that. 

But it still won't start from command prompt or just double clicking the file i have to start it from Windows Shell. weird

**Comment by Egoistically** [comment]
What's the output when starting it from cmd?

**Comment by Egoistically** [comment]
Closed for now.
