### ISSUE TITLE
Stuck on 7-1 boss

### ISSUE THREAD

**Issue by tazor21** [Egoistically/ALAuto#36]
The bot refuses to click on the boss fleet in 7-1. It keeps clicking on the area outside the map zone. The console doesn't detect the boss fleet it seems.
Edit: Just tested it on world 8-1. Seems like the small map is the problem, I guess.
![Untitled](https://user-images.githubusercontent.com/58846409/70792068-05237d80-1dcb-11ea-80d9-538de30077ac.png)

**Comment by JustShinobi** [comment]
are you using 5419ff2?
i have good results using them.

**Comment by tazor21** [comment]
Yeah, I was using the latest version.

**Comment by Egoistically** [comment]
For some reason it didn't detect the boss. Should fix itself by blacklisting that location, searching for another enemy and properly detecting the boss afterwards. 
Does it happen consistently?

**Comment by hjk22** [comment]
It can't find the boss because, for some reasons, in this map the boss icon is slightly bigger than the default one. If you want to farm this map you need to substitute the boss fleet asset.

**Comment by Egoistically** [comment]
> 
> 
> It can't found the boss because, for some reasons, in this map the boss icon is slightly bigger than the default one. If you want to farm this map you need to substitute the boss fleet asset.

Really?... I guess I can hardcode asset resizing for that map?

**Comment by Egoistically** [comment]
Should be fixed https://github.com/Egoistically/ALAuto/commit/bb11c2d57df6126c49c1513caf5879084e67dc70.
