### ISSUE TITLE
error after starting a commission

### ISSUE THREAD

**Issue by MetalDevOps** [Egoistically/ALAuto#39]
Every time I started a commission the bot stops and the reported error come up.

![](https://i.imgur.com/ttJAj9j.png)

**Comment by Egoistically** [comment]
What's your config.ini?

**Comment by JustShinobi** [comment]
> Enabled: false
> Map: 8-1
> OilLimit: 0
> RetireCycle: 2
> 
> [Modules]
> Commissions: true
> Enhancement: False
> Missions: false
> Retirement: false

I would like to stay just doing the commission

**Comment by Egoistically** [comment]
Should be fixed https://github.com/Egoistically/ALAuto/commit/652e00ec96937a0c1135564a8dd516f64cb45570.

**Comment by JustShinobi** [comment]
> Should be fixed [652e00e](https://github.com/Egoistically/ALAuto/commit/652e00ec96937a0c1135564a8dd516f64cb45570).

Works, thanks.
