### ISSUE TITLE
Error: Wrong resolution.

### ISSUE THREAD

**Issue by ArneJacob** [Egoistically/ALAuto#40]
Script won't run, citing that the resolution is not 1920x1080, even though within Bluestacks it is set to 1920x1080. I've tried setting a custom resolution to 1920x1080 as well, with the same results, and none of the 3 DPI settings below worked either. Fullscreen mode on Bluestacks did not work.

![image](https://user-images.githubusercontent.com/42345768/71289719-17bf2900-236e-11ea-8118-9f26fccf802b.png)

**Comment by JustShinobi** [comment]
looks like you are using a different version of BS.

![](https://i.imgur.com/aPBZKHn.png)

Mine is different from yours.

**Comment by ArneJacob** [comment]
Updated Bluestacks, it works now. Thanks!
