### ISSUE TITLE
no modele named cv2

### ISSUE THREAD

**Issue by EggsOnRamen** [Egoistically/ALAuto#41]

**Comment by Egoistically** [comment]
Give more details...

**Comment by EggsOnRamen** [comment]
sorry im new to this stuff, im trying to run this on my phone


C:\Users\utente\Desktop\ALAuto-master>python ALAuto.py
Traceback (most recent call last):
  File "ALAuto.py", line 3, in <module>
    from modules.combat import CombatModule
  File "C:\Users\utente\Desktop\ALAuto-master\modules\combat.py", line 3, in <module>
    from util.utils import Region, Utils
  File "C:\Users\utente\Desktop\ALAuto-master\util\utils.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Egoistically** [comment]
`pip3 install -r requirements.txt`

**Comment by EggsOnRamen** [comment]
i already had the requiremesnts installed

`C:\Users\utente\Desktop\ALAuto-master>pip3 install -r requirements.txt
Requirement already satisfied: opencv-python==3.4.4.19 in c:\users\utente\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 1)) (3.4.4.19)
Requirement already satisfied: scipy==1.1.0 in c:\users\utente\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: imutils==0.5.3 in c:\users\utente\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 3)) (0.5.3)
Requirement already satisfied: numpy>=1.14.5 in c:\users\utente\appdata\local\programs\python\python37\lib\site-packages (from opencv-python==3.4.4.19->-r requirements.txt (line 1)) (1.17.4)
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\utente\Desktop\ALAuto-master>python ALAuto.py
Traceback (most recent call last):
  File "ALAuto.py", line 3, in <module>
    from modules.combat import CombatModule
  File "C:\Users\utente\Desktop\ALAuto-master\modules\combat.py", line 3, in <module>
    from util.utils import Region, Utils
  File "C:\Users\utente\Desktop\ALAuto-master\util\utils.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'`

**Comment by hjk22** [comment]
Have you installed different versions of Python on your computer (for example you have installed both Python 2.7 and Python 3.7)?

**Comment by EggsOnRamen** [comment]
Thank you for your help, i did have another copy of python(microsoft store) because i couldt use pip when i first downloaded it.
Uninstalled the other version on python and ran the program.
