### ISSUE TITLE
Can't scan em at top location.

### ISSUE THREAD

**Issue by Walofz** [Egoistically/ALAuto#43]
if em spawn at top location. cv2 or picture in assets folder can't match it.

can add code to swipe up or something for small map ?

![image](https://user-images.githubusercontent.com/29043573/71342291-e5404680-258e-11ea-806d-9ce1beb83080.png)

**Comment by Egoistically** [comment]
Bad rng, can't do anything about it tbh... This map is just a pain.

**Comment by Walofz** [comment]
RNG SAMAAAAAAAA !!!
