### ISSUE TITLE
How do get the assets so i can add them for this event? 

### ISSUE THREAD

**Issue by ghost** [Egoistically/ALAuto#44]
How did you get all the pictures for the maps etc, etc. I would like to try and the maps for this event myself.

**Comment by Egoistically** [comment]
Execute `adb exec-out screencap -p > file.png` and then crop it with photoshop or whatever photo editor you have.

**Comment by ghost** [comment]
Is there a set resolution the screenshots have to be?

**Comment by Egoistically** [comment]
No, if you crop it correctly just leave it as it is.

**Comment by Egoistically** [comment]
https://github.com/Egoistically/ALAuto/wiki/Creating-new-assets-for-bot
