### ISSUE TITLE
Will this event be added?

### ISSUE THREAD

**Issue by MrJefferson-ChooChoo** [Egoistically/ALAuto#45]
Will this event be made available for the bot?

When i put E-A1 in the config file it doesn't work.

**Comment by Egoistically** [comment]
YoStar likes making totally unnecessary changes. 
This time the event button is called "Operation" instead of "Event", so the asset needs to be updated. Everything else should be fine though.

**Comment by ghost** [comment]
Where would i make that change? Also thanks for replying so fast on christmas.

**Comment by Egoistically** [comment]
I will push them in a few minutes, if you don't mind waiting. 
And it's fine, I'm at home anyway.

**Comment by ghost** [comment]
That's awesome, sure i don't mind.

**Comment by Egoistically** [comment]
https://github.com/Egoistically/ALAuto/commit/9945fc4a7a21b61119eca7703cbf488cfd8e98e0.

**Comment by ghost** [comment]
Awesome man thanks, 

And a merry christmas.

**Comment by JustShinobi** [comment]
> [9945fc4](https://github.com/Egoistically/ALAuto/commit/9945fc4a7a21b61119eca7703cbf488cfd8e98e0).

did not recognize the A2 map, the A1 recognized, anyway I do not intend to play in A2, just warning.

**Comment by Egoistically** [comment]
> 
> 
> Awesome man thanks,
> 
> And a merry christmas.

Hope it works, Merry Christmas! 

> 
> 
> did not recognize the A2 map, the A1 recognized, anyway I do not intend to play in A2, just warning.

Was told by @hjk22 event map assets weren't getting properly detected, tried to solve it by reducing similarity threshold but apparently not enough? Cannot do much about it since I don't have any way to get the them yet (still clearing second map).

**Comment by JustShinobi** [comment]
> > Awesome man thanks,
> > And a merry christmas.
> 
> Hope it works, Merry Christmas!
> 
> > did not recognize the A2 map, the A1 recognized, anyway I do not intend to play in A2, just warning.
> 
> Was told by @hjk22 event map assets weren't getting properly detected, tried to solve it by reducing similarity threshold but apparently not enough? Cannot do much about it since I don't have any way to get the them yet (still clearing second map).

Don't worry, I don't think anyone will farm on these maps, I just hope it works on B3 or D3

**Comment by ghost** [comment]
Yeah it's just clicking the same target it can't reach over and over.

**Comment by Egoistically** [comment]
What do you mean by "can't reach"?

**Comment by ghost** [comment]
You know the tiles outside of the fleet's reach? it's clicking on a enemy ship that's on a tile it can't reach.

**Comment by Egoistically** [comment]
Ah but of course that happens, bot does not support limited movement. This is intended for farming after you unlock clearing mode.

**Comment by ghost** [comment]
Mhhh, but i already cleared one and made it safe and the movement restriction is still there.

**Comment by Egoistically** [comment]
I was so tired I didn't understand what you were saying, clearing mode unlocks after making that map's threat level go down to safe. Sorry for the confusion.

**Comment by JustShinobi** [comment]
was not recognizing the A3 map with the asset you added, I managed to fix it here and it worked with that asset.

https://f.cyberdrop.xyz/map_E-A3-gT1YtFJp.rar

**Comment by JustShinobi** [comment]
fix C3 too

https://f.cyberdrop.xyz/map_E-C3-NFTdM5i6.rar

**Comment by JustShinobi** [comment]
C2 fix 

https://f.cyberdrop.xyz/map_E-C2-nR3Fj2YV.rar

**Comment by Egoistically** [comment]
@whoamikyo https://github.com/Egoistically/ALAuto/commit/d9f70dd47c2db532b3e1f08e0869988231ba21ba please tell me if it works fine.

**Comment by JustShinobi** [comment]
> @whoamikyo [d9f70dd](https://github.com/Egoistically/ALAuto/commit/d9f70dd47c2db532b3e1f08e0869988231ba21ba) please tell me if it works fine.

will try now, I was farming in C2 and always after 2 runs gave this error here, cant find the map.

you fix it too?

![](https://i.imgur.com/qur8SPz.png)

**Comment by Egoistically** [comment]
Was that before the update? And can you send the full log? I can't see what caused the crash there since it's cut.

**Comment by JustShinobi** [comment]
> Was that before the update? And can you send the full log? I can't see what caused the crash there since it's cut.

before update, the log was normal, basically after 2 runs the bot could no longer detect the map, I tested it several times and seemed to happen after 2 runs.

**Comment by Egoistically** [comment]
Ah I thought it was a crash rather than a manual exit, my bad.

**Comment by JustShinobi** [comment]
12 runs on C2  and any erros with laster build, seems ok for me.

**Comment by didzkows** [comment]
Regarding the config, since the wiki isnt updated. If using the latest build what do we put in the Event field?

> [Events]
Enabled: False
Event: Crosswave
Levels: EX,H,N,E

**Comment by JustShinobi** [comment]
> Regarding the config, since the wiki isnt updated. If using the latest build what do we put in the Event field?
> 
> > [Events]
> > Enabled: False
> > Event: Crosswave
> > Levels: EX,H,N,E

dont change this, to farm on C2 i'm using

[Combat]
Enabled: true
Map: E-C2

**Comment by Egoistically** [comment]
> 
> 
> Regarding the config, since the wiki isnt updated. If using the latest build what do we put in the Event field?

Updated the wiki, should be more clear now.

**Comment by Masuzu** [comment]
Thank you a lot for the quick updates!
I was just wondering, is there a way to switch to the second fleet and use it instead of the first fleet selected by default when you enter an event map?

**Comment by UserFromSpace** [comment]
Hello!

Masuzu, I might have a fix for you, but it's on map-to-map basis. Primitive, but werks.

1) Add a new region in combat.py. It's at the start of the script. /_Picture switch_0001.png_
2) Go to
 `def clear_map(self):
        Logger.log_msg("Started map clear.")
        Utils.script_sleep(2.5)

        #hide strat menu
        Utils.touch_randomly(self.region["hide_strat_menu"])`
Implement the click on the region, as present in _switch_0002.png_ and then fix the swipe. Utils.swipe(xs, ys, xf, yf, ms), where **x** is the abscissa, **y** ordinate. **s** is the start and **f** the finish. The last number represents the milliseconds.

That should be it! Good luck on your farming.

As to the new patches, might I suggest 1) Check if Fleet Lock is enabled.

Edit: I just realised my version is out of date, but the structure and logic behind it should remain the same.
![switch_0001](https://user-images.githubusercontent.com/34422941/71556625-b66d1900-2a43-11ea-9ec4-5b932040824f.PNG)
![switch_0002](https://user-images.githubusercontent.com/34422941/71555636-b9add800-2a36-11ea-8a74-bc5ae59f1178.PNG)

**Comment by didzkows** [comment]
was D3 supported? didn't see any mention of someone trying it. The sprite for the boss fleet may need to be added
additionally i'm getting the error "cannot find specified map", after the script opens the event map with the D3 node visible

**Comment by Egoistically** [comment]
Not added yet, only A and C for now. I have yet to finish clearing B and D. Expect an update in a few hours (hopefully)! 
You can also add the assets by yourself, more info here: https://github.com/Egoistically/ALAuto/issues/44.

**Comment by didzkows** [comment]
> Not added yet, only A and C for now. I have yet to finish clearing B and D. Expect an update in a few hours (hopefully)!
> You can also add the assets by yourself, more info here: #44.

Thank you, successfully updated the asset for [map_E-D3](https://i.imgur.com/Foqf68y.png)
Only issue is that it will obviously only work for the current event, not sure why the script wouldn't recognize the D3 on its own
Additionally the script keeps getting stuck and accidentally tapping the `Fleet Lock` button, and overall having trouble finding enemies, issue seems to be the fact that there are 3 siren spawns on D3, so if the script blacklists one of the few available enemy fleets then there isn't much to do. Is it possible to add certain sirens to the enemy assets folder and have them be seen as a target?
and finally, the script doesn't seem to recognize the boss fleet

**Comment by Egoistically** [comment]
Haven't gotten to D3 yet, @hjk22 has a fix for boss detection.

**Comment by hjk22** [comment]
I opened a new pull request #47 which should make farming in B3/D3 possible. I have tested it a little bit in B3 and it worked (needs more testing though). @Egoistically will review it and test it, and if there aren't any problems he will probably merge it tomorrow.

**Comment by Egoistically** [comment]
Regarding Sirens and fleet lock: https://github.com/Egoistically/ALAuto/commit/c39ac03c50a134310d20d80a7a57162e883d7e92.

**Comment by Egoistically** [comment]
Event finished.
