### ISSUE TITLE
Merge pull request #47 - Script gets stuck on E-D3 in certain cases

### ISSUE THREAD

**Issue by didzkows** [Egoistically/ALAuto#50]
Issue occurs when the available targets are the sirens and the remaining fleets are tucked away in the top and bottom left corners. 
The triangles that the script scans for aren't visible,
One is tucked away behind the list of ships in your active fleet, and the other is just tucked under the timer as such:

![Bluestacks_Yn172HG2qg](https://user-images.githubusercontent.com/55407472/71595417-85571c00-2b09-11ea-919c-b9a3f36fea49.png)

Another interesting situation where my fleet finds itself trapped behind a siren that is blocking the triangle leading to blacklisting and no progress

![Bluestacks_9XvxlHlVFW](https://user-images.githubusercontent.com/55407472/71596124-5a21fc00-2b0c-11ea-9c60-e99e80da722c.png)

As such there are no targets available and the script will just cycle between blacklisting points and do nothing.
This happens most commonly early on when there are few targets aside from the sirens available.

![cmd_KaXD0tTFdn](https://user-images.githubusercontent.com/55407472/71595482-dcf58780-2b09-11ea-951d-788fcd63700e.png)

Is it possible to integrate #48 in the event that the script is unable to find another target?
Or given that is an issue, make the script retreat and re-attempt the map (with the option to limit attempts so that it doesn't eat our oil if there is a recurring issue)
To clarify, this is on the latest build post merge

**Comment by Egoistically** [comment]
Easiest solution would be adding Sirens, ain't doing that though as explained here https://github.com/Egoistically/ALAuto/commit/c39ac03c50a134310d20d80a7a57162e883d7e92. I don't think there is any other way to fix it, I am very sorry.

**Comment by didzkows** [comment]
Added sirens and everything works well
