### ISSUE TITLE
Merge pull request #47 - Checking HQ, "Cat Lodge Alert"

### ISSUE THREAD

**Issue by didzkows** [Egoistically/ALAuto#51]
![HQ_alert](https://user-images.githubusercontent.com/55407472/71596527-afaad880-2b0d-11ea-8385-c2dbb8aa48ce.png)
 
Just a small thing to point out, the alert in my case was for the Academy, not cat lodge (so the script failed to correctly identify the alert) Not sure whether this may cause an issue for others based on their config file.

```
[Headquarters]
Dorm: True
Academy: False
SkillBookTier: 2

[Modules]
Commissions: True
Enhancement: False
Missions: False
Retirement: False
```

In my case i am not automating any Skill training so the check doesn't matter, and to clarify i am using the latest build as of this time.

**Comment by hjk22** [comment]
Thanks for pointing this out, I will look into it.

**Comment by hjk22** [comment]
da8352a6926f50e7dfd2b8be63b8474fe760551c should fix the issue. I had made the cat_lodge_alert asset too big, so the match value was over 0.99 even if there wasn't any alert icon.

**Comment by JustShinobi** [comment]
Hey @hjk22 I saw that you made the pull request for chapters 9 and 10, how about adding support for chapters 11 and 12? even if only in the smaller maps like 11-1, 11-2 and 12-1, 12-2, I already have the assets ready, just need to optimize the code.

**Comment by hjk22** [comment]
Sure, I can add them if you provide me the assets, or at least the map selection's screenshots, since the last node I cleared was 10-4. What do you mean by "optimizing" the code? Do these maps need some kind of support?

**Comment by JustShinobi** [comment]
here the assets: https://drive.google.com/a/swccd.edu/file/d/16LNkbhk52QSXZ9GFyHJ55k_hhClmu78N/view?usp=drivesdk

I just made this code modification, but I'm not sure if this is enough to work well, at least 12-1 is working well.

combat.py
```python
else:
    for x in range(1, 13):
        if Utils.find("maps/map_{}-1".format(x), 0.99):
            _map = x
            break
```
config.py
```python
        if self.combat['enabled']:
            map = self.combat['map'].split('-')
            valid_chapters = list(range(1, 13)) + ['E']
            valid_levels = list(range(1, 5)) + ['A1', 'A2', 'A3', 'A4',
                                                'B1', 'B2', 'B3', 'B4',
                                                'C1', 'C2', 'C3', 'C4',
                                                'D1', 'D2', 'D3', 'D4',
                                                'SP1', 'SP2', 'SP3']
```

**Comment by hjk22** [comment]
Thank you for the assets! Yes, those changes should be enough iirc, I'll check just in case.

**Comment by hjk22** [comment]
I tried your assets (map_11-1.png) and the bot couldn't detect it. I tried making this asset myself and my pic's background color was slightly different from the one of the pic you uploaded, yours was a bit more saturated. I checked the hexadecimal values to be sure and they indeed were different. I don't know (and can't check) if the other assets are affected by the same problem, so I can't push these changes.

**Comment by JustShinobi** [comment]
> I tried your assets (map_11-1.png) and the bot couldn't detect it. I tried making this asset myself and my pic's background color was slightly different from the one of the pic you uploaded, yours was a bit more saturated. I checked the hexadecimal values to be sure and they indeed were different. I don't know (and can't check) if the other assets are affected by the same problem, so I can't push these changes.

My bad, I sent the wrong file.

here the correct file:
https://drive.google.com/a/swccd.edu/file/d/1S5OhradnFpCQQIWCN7C6itYDmAqbH96z/view?usp=drivesdk

**Comment by JustShinobi** [comment]
I checked and 12-3 and also sent the wrong version too, had multiple versions of assets for some reason.

btw, I deleted the wrong versions and tested them one by one and they are all working.

here the V2 files

https://drive.google.com/a/swccd.edu/file/d/1qqe1MlRksB8Ft3zshG6jnYl2BEB63CHX/view?usp=drivesdk

**Comment by hjk22** [comment]
Closing this issue since the original one has been solved and the additional request has been implemented by @Egoistically.
