### ISSUE TITLE
commission module is broken

### ISSUE THREAD

**Issue by Fredwuz** [Egoistically/ALAuto#53]
when I start the bot it wont do commissions at least start them

**Comment by kyO-NinjA** [comment]
commissions is working fine here dude, explain better.

**Comment by Fredwuz** [comment]
before I updated it worked but after I updated it wont start any commission I had the bot running for about an hour and it wouldnt start any commission
I am using Bluestacks and the leatest version from github
this is my config I disabled the combat for faster testing if it works
 
```
[Network]
Service: 127.0.0.1:5555

[Updates]
Enabled: True
Channel: Development

[Combat]
Enabled: False
Map: E-A1
OilLimit: 1000
RetireCycle: 2
RetreatAfter: 0

[Headquarters]
Dorm: True
Academy: True
SkillBookTier: 3

[Modules]
Commissions: True
Enhancement: True
Missions: True
Retirement: True

[Events]
Enabled: False
Event: Crosswave
Levels: EX,H,N,E
```

**Comment by JustShinobi** [comment]
does an error happen?

**Comment by Egoistically** [comment]
Be more specific.

**Comment by didzkows** [comment]
To debug i suggest disabling the other options and just leaving commissions on. 
If it works then enable another option and recheck.
Will help isolate where the issue may be.

**Comment by D4rkAng31** [comment]
It could be that you are/have just reached commander level 50 and the game isn't recommending a suitable ship (has to be lvl 100) that can do the commission. Check if the bottom commission requires a lvl 100 ship and if you can use the recommend option. If you can't then I guess you'll have to do commissions manually like I do.

**Comment by Fredwuz** [comment]
ohh yeah it could be this beacuse recently I reached lvl 50 thanks
