### ISSUE TITLE
 "Resolution is not 1920x1080"

### ISSUE THREAD

**Issue by RubySapior** [Egoistically/ALAuto#54]
I'm running on Nox android 5 and have have checked the 1080p option. Am I missing anything else?
https://ibb.co/PN87yVB

**Comment by Egoistically** [comment]
Run `adb shell wm size` on a cmd and send me the output.

**Comment by RubySapior** [comment]
When I type "adb shell wm size" into cmd
https://ibb.co/C1TVQvP

**Comment by JustShinobi** [comment]
updade your adb files.

**Comment by RubySapior** [comment]
Google Usb driver on Android SDK?

**Comment by RubySapior** [comment]
@whoamikyo Is this the adb file updater or do I need anything else? 
https://forum.xda-developers.com/showthread.php?t=2588979

Update:
Im now getting this
https://ibb.co/WsKY6JZ

However, nothing happens in-game.

**Comment by JustShinobi** [comment]
> @whoamikyo Is this the adb file updater or do I need anything else?
> https://forum.xda-developers.com/showthread.php?t=2588979
> 
> Update:
> Im now getting this
> https://ibb.co/WsKY6JZ
> 
> However, nothing happens in-game.

what bluestacks version are you using?

edit: try use lastest bluestack version, NOX sucks.

**Comment by RubySapior** [comment]
@whoamikyo 
Just going to make sure before i move to Bluestack
So in the Nox/Bin cmd, I do "nox_adb.exe connect 127.0.0.1:62025"
and in the config file, i also put "127.0.0.1:62025"
Or am i typing this wrong?

**Comment by JustShinobi** [comment]
i dont know nox adb port, but BS adb port is 127.0.0.1:5555

**Comment by JustShinobi** [comment]
but I think if the problem were it would give a connection error.

**Comment by JustShinobi** [comment]
no need to type adb connect either, only put on config file.

**Comment by RubySapior** [comment]
Now on Bluestack.
Nothing happens after that line
https://ibb.co/p4KLh45

**Comment by JustShinobi** [comment]
can you paste your config file?

**Comment by Walofz** [comment]
download and set path adb step by step from xda.

> https://www.xda-developers.com/install-adb-windows-macos-linux/

**Make sure you disable and delete old adb files .**

for Windows user set path for use adb

> System > Advanced system settings > Tab Advanced > Enivronment Variables... > Path > Edit

![image](https://user-images.githubusercontent.com/29043573/71783401-e191d280-3018-11ea-9e79-1b24aa1560bb.png)

by default port adb bluestack is `5555` and check for use adb in app

![image](https://user-images.githubusercontent.com/29043573/71783358-3bde6380-3018-11ea-9f4a-76211808af9c.png)

i don't recommend use Nox, it's stuck and very use ram and cpu.

**result**
![image](https://user-images.githubusercontent.com/29043573/71783455-84e2e780-3019-11ea-944f-cbb3e793a61f.png)


Goodluck.

**Comment by RubySapior** [comment]
@Walofz 
Still not doing anything
[
![image](https://user-images.githubusercontent.com/39416683/71812179-5f5ed980-302b-11ea-8b95-f9a87e07f3f2.png)
](url)

Found a device
[
![image](https://user-images.githubusercontent.com/39416683/71812246-8e754b00-302b-11ea-8258-d055eb3f398c.png)
](url)

Added all 4 directories into environment variables > path
[
![image](https://user-images.githubusercontent.com/39416683/71812350-d5fbd700-302b-11ea-9fa7-7416a388d874.png)
](url)

and did the check mark thing in Bluestack

**Comment by RubySapior** [comment]
@whoamikyo 

Config File

[Network]
Service: 127.0.0.1:5555

[Updates]
Enabled: True
Channel: Development

[Combat]
Enabled: True
Map: 3-4
OilLimit: 1000
RetireCycle: 2
RetreatAfter: 0

[Headquarters]
Dorm: True
Academy: True
SkillBookTier: 2

[Modules]
Commissions: True
Enhancement: True
Missions: True
Retirement: False

[Events]
Enabled: True
Event: Crosswave
Levels: EX,H,N,E

**Comment by JustShinobi** [comment]
> @whoamikyo
> 
> Config File
> 
> [Network]
> Service: 127.0.0.1:5555
> 
> [Updates]
> Enabled: True
> Channel: Development
> 
> [Combat]
> Enabled: True
> Map: 3-4
> OilLimit: 1000
> RetireCycle: 2
> RetreatAfter: 0
> 
> [Headquarters]
> Dorm: True
> Academy: True
> SkillBookTier: 2
> 
> [Modules]
> Commissions: True
> Enhancement: True
> Missions: True
> Retirement: False
> 
> [Events]
> Enabled: True
> Event: Crosswave
> Levels: EX,H,N,E

Test with this cfg

[Network] 
Service: 127.0.0.1:5555

[Updates]
Enabled: True
Channel: Development

[Combat]
Enabled: true
Map: 3-4
OilLimit: 0
RetireCycle: 2
RetreatAfter: 0

[Headquarters]
Dorm: True
Academy: False
SkillBookTier: 2

[Modules]
Commissions: True
Enhancement: False
Missions: False
Retirement: False

[Events]
Enabled: False
Event: Crosswave
Levels: EX,H,N,E

**Comment by RubySapior** [comment]
@whoamikyo 
Still nothing changed from config  :(

**Comment by JustShinobi** [comment]
still getting this?

![](https://i.ibb.co/DLKSt2h/Annotation-2020-01-04-015727.jpg)

**Comment by Walofz** [comment]
@RubySapior Python version ?

**Comment by JustShinobi** [comment]
> @RubySapior Python version ?

I was also going to ask that.

on CMD type python --version

**Comment by RubySapior** [comment]
@whoamikyo @Walofz 
Using Python 3.7.2
[
![image](https://user-images.githubusercontent.com/39416683/71838730-5fcc9400-306e-11ea-9aed-1e0e90ee5934.png)
](url)

**Comment by ghost** [comment]
I had this happen to me once.
Go back to Nox.
Make sure you choose tablet and not phone in your resolution settings.
Then restart your emulator and click Restore window size after restarting. It should work.

![resolution](https://user-images.githubusercontent.com/59578827/71842093-cbfec600-3075-11ea-8f32-82edf2fc2ac7.png)

**Comment by RubySapior** [comment]
@talktocat 
Both my nox and bluestack were at Tablet and 1080p settings
[
![image](https://user-images.githubusercontent.com/39416683/71843192-2bf66c00-3078-11ea-81f7-a462d0018eed.png)
](url)

**Comment by RubySapior** [comment]
I guess ill close this issue cause the "Resolution is not 1920x1080" has been solved.
Ill open another issue for the python script not working after connecting to device.
