### ISSUE TITLE
Nothing happens after  "Successfully connected to the service"

### ISSUE THREAD

**Issue by RubySapior** [Egoistically/ALAuto#55]
[
![image](https://user-images.githubusercontent.com/39416683/71843722-5d236c00-3079-11ea-9ec3-9bd4b7c7edf0.png)
](url)

**Comment by RubySapior** [comment]
OOOOO after retrying on a new device, it WORKS :D
i dont know why or what changed

**Comment by Egoistically** [comment]
Glad it got solved though!
