### ISSUE TITLE
Suggestion: script will look for enemy fleets if it blacklists after a certain number of times.

### ISSUE THREAD

**Issue by D4rkAng31** [Egoistically/ALAuto#56]
What if after 5-7 Blacklists, the script will begin to hunt for enemy fleets using code from the dorm. I do not really know how to code myself so it's just a suggestion, as it might solve the problem of the script when no enemy fleets are found.

**Comment by JustShinobi** [comment]
Or, how about after a considerable number of blacklists, get off the map and start over?

**Comment by hjk22** [comment]
To be honest, I don't really feel the need to add this kind of feature right now, but it still is a nice idea and it will be probably implemented sooner or later.
Thank you both for your suggestions!

**Comment by Egoistically** [comment]
Couldn't implement what @whoamikyo suggested because of how the code is organized. However, I added OP's suggestion: https://github.com/Egoistically/ALAuto/commit/97e8717b308ee2d2801b73a52408a65af6e3faec.

**Comment by hjk22** [comment]
Closing this issue since the suggestion proposed by OP has been implemented by @Egoistically.
