### ISSUE TITLE
Random crashes on new fight

### ISSUE THREAD

**Issue by sskver** [Egoistically/ALAuto#61]
It randomly crashes, sometimes it shows insufficent memory from OpenCV but it doesnt even use more than 500mbs of ram.
Config: 
AMD Fx 8350 4.2GHz
16GB Ram
RX 480 8GB
![memory](https://user-images.githubusercontent.com/32797351/72212629-ab07fc00-34df-11ea-9387-e42b38363671.png)

![crash](https://user-images.githubusercontent.com/32797351/72212624-975c9580-34df-11ea-9b9e-917c536856fb.png)

**Comment by sskver** [comment]
Setting "set OPENCV_OPENCL_DEVICE=AMD:GPU:Polaris"
Fixes the issue

**Comment by Al12rs** [comment]
How did you get to the conclusion of doing that?

**Comment by sskver** [comment]
Some other guy posted the same issue. My friend didnt had the issue with an nvidia card. I tried forcing the use of the gpu and it just worked.

**Comment by Al12rs** [comment]
Huh...

**Comment by sskver** [comment]
It's been running for 1 hours+ and no insufficent memory error or crashes.

**Comment by Egoistically** [comment]
I'm surprised that was the problem, I didn't know what the issue was since it never happened to me. Glad to see you fixed it!

**Comment by sskver** [comment]
It's really weird, not gonna lie. OpenCV even tells me that the GPU couldn't be found but it uses the GPU. ¯\_(ツ)_/¯
