### ISSUE TITLE
Tactical Class stuck in loop if someone's skill is maxed lv 10

### ISSUE THREAD

**Issue by phantasmalmira** [Egoistically/ALAuto#63]
Basically the script continue tapping on the confirm button of skill lesson ended when the prompt is actually about the skill being maxed, no idea if this issue is present in EN since I don't know how the prompt looks, I imagine it's the same though.

Prompt showing Noshiro finished enhancing, skill level 9 -> 10
![hqskill](https://user-images.githubusercontent.com/55663494/72218958-adb82f00-357b-11ea-8345-323163f05a2b.png)

**Comment by Al12rs** [comment]
I'll fix this Monday...

**Comment by hjk22** [comment]
Yes, thank you for pointing this out, I should have fixed this now alongside another issue that happens when the skillbooks are finished. Tomorrow I will test it and if there aren't any problems I will push it.

**Comment by phantasmalmira** [comment]
Nice, thanks! The 2 jp assets that are not common for the new HQ is in the pull request.
