### ISSUE TITLE
Out of memory?

### ISSUE THREAD

**Issue by teammate165** [Egoistically/ALAuto#64]
I've encountered this error twice now. I forgot to keep the logs when it first happened but seems to happen if I keep it running for ~2 hours

traceback.txt
```Traceback (most recent call last):
  File "ALAuto.py", line 218, in <module>
    script.run_sortie_cycle()
  File "ALAuto.py", line 79, in run_sortie_cycle
    self.run_combat_cycle()
  File "ALAuto.py", line 87, in run_combat_cycle
    result = self.modules['combat'].combat_logic_wrapper()
  File "E:\ALAuto\modules\combat.py", line 100, in combat_logic_wrapper
    if not self.clear_map():
  File "E:\ALAuto\modules\combat.py", line 393, in clear_map
    target_info = self.get_closest_target(self.blacklist)
  File "E:\ALAuto\modules\combat.py", line 553, in get_closest_target
    enemies = self.get_enemies(blacklist)
  File "E:\ALAuto\modules\combat.py", line 479, in get_enemies
    l5 = filter(lambda x:x[1] > 80 and x[1] < 977 and x[0] > 180, map(lambda x:[x[0] + 75, x[1] + 110], Utils.find_all('enemy/fleet_3_down', sim - 0.06, self.chapter_map)))
  File "E:\ALAuto\util\utils.py", line 217, in find_all
    match = cv2.matchTemplate(screen, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp:55: error: (-4:Insufficient memory) Failed to allocate 16612808 bytes in function 'cv::OutOfMemoryError'
```

I have 2x4GB DDR3 installed in my system. Here's the full operation log: https://pastebin.com/QrCQXcjE

**Comment by sskver** [comment]
I was thinking that it might be a problem with amd graphics cards. Do you use an amd card?

**Comment by teammate165** [comment]
I do, I'm using RX 580 4GB

**Comment by sskver** [comment]
I'm going to try to do a workaround with forcing opencv to use amdgpu.
Edit:
You could try setting
"set OPENCV_OPENCL_DEVICE=AMD:GPU:Polaris"
before starting the python script.

**Comment by sskver** [comment]
Seems to have fixed the issue for me.

**Comment by hjk22** [comment]
@teammate165 Was the fix provided skver0 able to solve your problem?

**Comment by teammate165** [comment]
Where do I insert that line?
Sorry for late response, I've been busy lately and didn't have much time to use or test the bot.

Edit: I added the line my start batch file, doesn't return any error so that's the way to go I guess? I'll report back the results after this session

**Comment by teammate165** [comment]
The fix @skver0 suggested worked like a charm, I'll be closing this issue now.
Please add an entry about this in the Wiki or ReadMe :D

**Comment by hjk22** [comment]
Thank you for your feedback and I'm glad it worked for you too!
