### ISSUE TITLE
Stuck on level requirement commisions

### ISSUE THREAD

**Issue by naTlatsyrC** [Egoistically/ALAuto#68]
Hello, I've noticed that the bot gets stuck when trying to start high-level requirement commissions.

I have 2+ ≥ ship level requirement.
They are not in any sortie.
They are unlinked from a formation.
![Bluestacks_7FhltyBonk](https://user-images.githubusercontent.com/16968714/72396071-c1d56b00-36f8-11ea-945f-bb5959fa6a8d.png)
![Bluestacks_PbixIZqptS](https://user-images.githubusercontent.com/16968714/72396051-b5e9a900-36f8-11ea-890b-57977051905d.png)

The bot repeatedly attempts to click recommend on the lowest commission which is a level 100 (I have a level 100, but it won't show up when recommend is clicked) 
![Bluestacks_g6fhNMq2Kt](https://user-images.githubusercontent.com/16968714/72396081-c732b580-36f8-11ea-9bd0-9cabf3a38a31.png)

The same happens on level 70 commissions despite having 2+ ships that are 70+
![Bluestacks_Qdq1REdLOs](https://user-images.githubusercontent.com/16968714/72396094-d6196800-36f8-11ea-8dbf-bef87bb13138.png)

I think it should either check to see:
If the dialog popping up saying it can't do the commission comes up
Or if it's previously pressed the bottom one and it didn't work to try the next one in line (By way of blacklist or something)

**Comment by JustShinobi** [comment]
The ship remains blocked for several reasons, for example... if you have made a fleet on some hard map with these ships, they will be blocked, however you can add them manually.

**Comment by naTlatsyrC** [comment]
> 
> 
> The ship remains blocked for several reasons. For example... if you have made a fleet on some hard map with these ships, they will be blocked. However, you can add them manually.

After removing said ships from hard-mode fleets issue no longer occurs.

Thank you for the help despite this being more of a game problem then the bot <3
