### ISSUE TITLE
Bug after update patch again.

### ISSUE THREAD

**Issue by Walofz** [Egoistically/ALAuto#69]
in this case
retire don't work, i think theyyyyy change font confirm.

![image](https://user-images.githubusercontent.com/29043573/72520628-6a680400-388c-11ea-9415-678f582d91e2.png)

**Comment by JustShinobi** [comment]
Will check in few minutes.

**Comment by Walofz** [comment]
Button "Confirm" will change.
i capture new and replace it, work again.

**Comment by Walofz** [comment]
i add pull requests #70 

only change 1 file.

**Comment by Egoistically** [comment]
That's all the update has changed?

**Comment by JustShinobi** [comment]
> That's all the update has changed?

I didn't see any other changes at the moment, combat and commission module runs fine.

**Comment by Walofz** [comment]
hmm why only me .... button "Confirm", i wait 2 min for check it, script don't click this button,when i recap it work again. or it's rare bug only me ?

**Comment by Walofz** [comment]
if all script still work, please reject my pull requests.

thank you.

**Comment by JustShinobi** [comment]
> hmm why only me .... button "Confirm", i wait 2 min for check it, script don't click this button,when i recap it work again. or it's rare bug only me ?

well, I could not test yet, as I am testing  other modules I am not using the retirement module.

**Comment by Walofz** [comment]
i'll test my new code when i commit,it will show in master project ?

i'm new in github, only use gitlab

**Comment by JustShinobi** [comment]
> i'll test my new code when i commit,it will show in master project ?
> 
> i'm new in github, only use gitlab

Not sure if I understand, but I think you have to do PR.

Other tip, when you are testing, use -d for debug.

**Comment by Walofz** [comment]
> Not sure if I understand, but I think you have to do PR.
> 
> Other tip, when you are testing, use -d for debug.

i'll re-write new project and add new feature on my new branch (dev), when i merge from dev branch to master branch (fork from main project), it's will show at main project or only show at my fork project ?

Sorry for my English.

**Comment by JustShinobi** [comment]
> > Not sure if I understand, but I think you have to do PR.
> > Other tip, when you are testing, use -d for debug.
> 
> i'll re-write new project and add new feature on my new branch (dev), when i merge from dev branch to master branch (fork from main project), it's will show at main project or only show at my fork project ?
> 
> Sorry for my English.

Only on your fork, you need to do a PR on main project.

**Comment by Walofz** [comment]
> Only on your fork, you need to do a PR on main project.

thank you very much.
