### ISSUE TITLE
New Comission Info after battle gets the bot stuck

### ISSUE THREAD

**Issue by jorge42222** [Egoistically/ALAuto#72]
So it seems the bot doesn't handle if after the battle there is a comission announcement and it gets stuck.
![Untitled](https://user-images.githubusercontent.com/60000039/72607877-21668d00-392a-11ea-9181-6da0c2928384.png)

**Comment by phantasmalmira** [comment]
Hey, the bot does handle the urgent commission notifications, however in the recent update, it seems that some have their 「Confirm」 button slightly changed? I'm not on EN server so I wouldn't know, refer to issue #69 . 

IT does look to have changed slightly in font, so in order for it to work again, you would have to get the updated asset for the confirm button, try using [this asset](https://github.com/Walofz/ALAuto/blob/860379e9187ee9cfc703a448a9267ab863bd33c4/assets/EN/commission/button_confirm.png) instead, it's from the author of #69 . Download it and copy to assets/EN/commission/ to overwrite button_confirm.png. If it still doesn't work, try getting your own 「Confirm」 asset instead, check [here](https://github.com/Egoistically/ALAuto/wiki/Creating-new-assets-for-bot) for how.

**Comment by JustShinobi** [comment]
already fix this on PR #71, waiting for merge, you can use my fork for while.

**Comment by Walofz** [comment]
> Hey, the bot does handle the urgent commission notifications, however in the recent update, it seems that some have their 「Confirm」 button slightly changed? I'm not on EN server so I wouldn't know, refer to issue #69 .
> 
> IT does look to have changed slightly in font, so in order for it to work again, you would have to get the updated asset for the confirm button, try using [this asset](https://github.com/Walofz/ALAuto/blob/860379e9187ee9cfc703a448a9267ab863bd33c4/assets/EN/commission/button_confirm.png) instead, it's from the author of #69 . Download it and copy to assets/EN/commission/ to overwrite button_confirm.png. If it still doesn't work, try getting your own 「Confirm」 asset instead, check [here](https://github.com/Egoistically/ALAuto/wiki/Creating-new-assets-for-bot) for how.

yes, button "Confirm" is change. i replace it new, script is work again.

**Comment by Walofz** [comment]
> So it seems the bot doesn't handle if after the battle there is a comission announcement and it gets stuck.
> ![Untitled](https://user-images.githubusercontent.com/60000039/72607877-21668d00-392a-11ea-9181-6da0c2928384.png)

for manual you download from my fork and replace at 2 location. (confirm by me)

[button_confirm](https://github.com/Walofz/ALAuto/blob/master/assets/EN/commission/button_confirm.png)
> assets/EN/commission/button_confirm.png

[skill_confirm_button](https://github.com/Walofz/ALAuto/blob/master/assets/EN/headquarters/skill_confirm_button.png)
> assets/EN/headquarters/skill_confirm_button.png

**Comment by Egoistically** [comment]
Yaaaa, you know, I was wondering what to do. I'm sorry for the delay. Updated and should be fixed https://github.com/Egoistically/ALAuto/commit/c892978d59d383d4d61c9b13f81ba4649429705c.

**Comment by jorge42222** [comment]
I tested it. It works with the new version.
