### ISSUE TITLE
DOCs and Nox

### ISSUE THREAD

**Issue by latot** [Egoistically/ALAuto#73]
Hi!, thx for this app :D 

I read the README and about the nox player and i just want to clarify something about that, there is a page that is a fake with malware saying "download nox", this happen a lot of time..., i think you will understand this with the page:

https://noxofficial.com

While the real webpage is:

http://www.bignox.com

They get a very similiar style with the page, and a very...., umconfortable name for who doesn't know the real webpage.....

I would like if you can specify the real page in the README.

The actual link about the installer installing extra software can be useful, not just with Nox, actually there is a lot, a lot of software that install things in that way, because ppl do "next>next>next" without read, i think is good warn about this, but split from the Nox fake site plis.

Thx.

**Comment by Egoistically** [comment]
I know which is the real website, that doesn't change the fact that the **official** Nox download did install malware through updates **without ever prompting the users**. And I know people who were affected by this. 
Their response to all this drama? That the malware was "useful software", "harmless" and other nonsense.

I'd rather not promote a shady emulator flooded with bullshit telemetry ran by a random chinese company after such a scandal happened. **Please, just avoid using Nox.**
