### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Darkaxis** [Egoistically/ALAuto#84]
i tried to run this on android using termux
It works but only up to starting a stage
after that it returns an error
  

can you do something abt this
it will be appreciated
you might want this [traceback.log](https://github.com/Egoistically/ALAuto/files/4208380/traceback.log)

**Comment by hjk22** [comment]
I'm not familiar with termux, but from what you reported it seems it lacks some implementations needed to handle multithreading. The only way to make the bot work on termux right now is to disable the multithreaded part of the script.
Comment lines from 295 to 313 in utils.py and change all the `Utils.find_in_scaling_range("enemy/fleet_boss")` in combat.py to `Utils.find("enemy/fleet_boss", 0.9)`.
The bot will not be at its best, but it still works well enough. Be aware that on maps like 2-4 and 7-1, which have a different zoom level, the bot will not work with these edits.

**Comment by Darkaxis** [comment]
it followed what you said
and it works
ill use it in fox mines
also thank you very much

**Comment by JASHUV** [comment]
@Darkaxis can you share the details and steps that how you run it on Android,? I'm unable install opencv properly in termux.. tell me whole process step by step pls.
