### ISSUE TITLE
NetEase MuMu "Resolution is not 1920x1080"

### ISSUE THREAD

**Issue by empathist-dot** [Egoistically/ALAuto#85]
Hello, 
I know it's said that this app was only tested on BS and Nox, but I have a very low-end PC and I can't run those. I'm trying to get AL auto to work on MuMu, can someone please help me?

I've set the screen resolution to 1920*1080.
I get the following error:
> Resolution is not 1920x1080, please change it.

Even though using `adb shell wm size` returns
> Physical size: 1920x1080

![image](https://user-images.githubusercontent.com/61105263/74600623-76fe9880-5094-11ea-81a4-5d196b9d5796.png)

Is there anyway to fix this or to just bypass the screen resolution test? Thanks in advance.

**Comment by vuhuynhphi12** [comment]
![image](https://user-images.githubusercontent.com/17667077/74603861-b2c44d00-50ea-11ea-8875-aab0e9a82b78.png)

Mine works well, just try reset the emulator or reset the PC

**Comment by hjk22** [comment]
If what the other user suggested didn't work and you're sure that you have configured everything correctly, you can disable the resolution check by commenting lines from 191 to 195 of ALAuto.py.
By the way, if you type `adb exec-out wm size`, what does it say?

**Comment by empathist-dot** [comment]
> Mine works well, just try reset the emulator or reset the PC

Maybe we don't have the same versions? I have the 1.16.3 Chinese edition.

`adb exec-out wm size` says 
> error: closed

Which is the same error I got after commenting lines 191 to 195.
![image](https://user-images.githubusercontent.com/61105263/74708761-b3113500-521d-11ea-92af-876f4f0ab5ac.png)

traceback.log:
> Traceback (most recent call last):
  File "ALAuto.py", line 204, in <module>
    Utils.update_screen()
  File "C:\Users\aemoh\Desktop\ALAuto-master\util\utils.py", line 86, in update_screen
    screen = cv2.imdecode(numpy.fromstring(Adb.exec_out('screencap -p'), dtype=numpy.uint8), 0)
cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:750: error: (-215:Assertion failed) !buf.empty() && buf.isContinuous() in function 'cv::imdecode_'

**Comment by vuhuynhphi12** [comment]
> Maybe we don't have the same versions? I have the 1.16.3 Chinese edition.

![image](https://user-images.githubusercontent.com/17667077/74713343-0190f480-525b-11ea-9303-42249b3373ae.png)

Maybe you can try this version (latest global). 2.2.19.1. Hope this helps you

**Comment by hjk22** [comment]
It seems that it fails to execute `adb exec-out` and the only reason I can think of for this to happen is that your emulator is running an Android version older than the one we recommend.
The easiest solution is to update your emulator as vuhuynhphi12 suggested. The other one would be to change all the `Adb.exec_out` in the code with `Adb.shell`, installing [sed](http://gnuwin32.sourceforge.net/packages/sed.htm) and adding it to path, and then launching the bot in legacy mode (`python ALAuto.py -l`), but I wouldn't recommend this.

**Comment by empathist-dot** [comment]
Thank you both, I updated the emulator and now it's connected. The only problem now is that it's doing nothing? I've read the installation guide and the wiki and enabled most stuff in config.ini

![image](https://user-images.githubusercontent.com/61105263/74939658-8f521880-53f0-11ea-9086-18725433ce13.png)

Is there a shortcut to start the bot or something?

**Comment by empathist-dot** [comment]
So I just updated the emulator and now there is no error, except it stops here now 

![image](https://user-images.githubusercontent.com/61105263/74940527-d7be0600-53f1-11ea-9c68-6ab56e55496a.png)

No errors or anything, it just stops. I redownloaded the zip this morning so I don't think I changed anything other than the config file. What do you think?

Edit: If this is normal, how do I start the bot? it is also not doing anything despite commissions and missions being ready.

**Comment by empathist-dot** [comment]
Here is the config.ini. I tried using one combat alone but nothing happens too.

`[Network]
Service: 127.0.0.1:7555

[Updates]
Enabled: True
Channel: Development

[Assets]
Server: EN

[Combat]
Enabled: True
Map: 3-4
BossFleet: False
OilLimit: 1000
RetireCycle: 2
RetreatAfter: 0
HideSubsHuntingRange: False
SmallBossIcon: False
SirenElites: False

[Headquarters]
Dorm: False
Academy: True
SkillBookTier: 2

[Modules]
Commissions: True
Enhancement: False
Missions: True
Retirement: True

[Events]
Enabled: False
Event: Royal_Maids
Levels: EX,H,N,E
IgnoreRateUp: False`

**Comment by empathist-dot** [comment]
Here is the config.ini. I tried using combat alone but nothing happens too.

```
[Network]
Service: 127.0.0.1:7555

[Updates]
Enabled: True
Channel: Development

[Assets]
Server: EN

[Combat]
Enabled: True
Map: 3-4
BossFleet: False
OilLimit: 1000
RetireCycle: 2
RetreatAfter: 0
HideSubsHuntingRange: False
SmallBossIcon: False
SirenElites: False

[Headquarters]
Dorm: False
Academy: True
SkillBookTier: 2

[Modules]
Commissions: True
Enhancement: False
Missions: True
Retirement: True

[Events]
Enabled: False
Event: Royal_Maids
Levels: EX,H,N,E
IgnoreRateUp: False
```

**Comment by Egoistically** [comment]
For some reason `adb exec-out screencap` isn't returning a valid image, so it just gets stuck. Try what @hjk22 said.

**Comment by empathist-dot** [comment]
Turns out I didn't have the latest ADB drivers. My bad. 

It's now working great! Really slow: 54 minutes for two clears of SP-3 (maybe too slow due to some problem?) but that's fine since it seems pretty stable, I don't mind it.
Anyway, to conclude, the solution to my errors was updating both ADB and MuMu.

Thanks, everyone!

**Comment by empathist-dot** [comment]
Nevermind it's way too slow.. I don't think 1.98/hour is normal? What's the average speed?

**Comment by empathist-dot** [comment]
Nevermind it's way too slow lmao. I don't think 1.98/hour is normal? What's the average speed?

**Comment by JustShinobi** [comment]
> Nevermind it's way too slow lmao. I don't think 1.98/hour is normal? What's the average speed?

the speed will depend on the fleet you use to clear and your PC specs, if you are using MuMu it's probably because you have a potato PC...

btw, 5 per hour here, but i have a ryzen 2600 with a GTX 970.

**Comment by vuhuynhphi12** [comment]
R5 2600 + 1660 here, still using mumu lol
But I have ~ 4.5 runs / hour

**Comment by empathist-dot** [comment]
I see, indeed I have an extremely potato laptop. Gt525m iirc. I have a SD 845 phone so wish I could use the bot on that, but the resolution doesn't fit because of notch. 

Well then it can't be helped, thanks again everyone.
