### ISSUE TITLE
On E-D3 bot will swap fleets on accident when searching for enemies

### ISSUE THREAD

**Issue by didzkows** [Egoistically/ALAuto#99]
Issue seems to stem from the secondary fleet being accidentally detected as an enemy node, and subsequently selected as a travel destination. 
Bot will then swap fleets and blacklist the area, continuing clear as normal with the secondary fleet, before eventually swapping back to the first fleet to clear the boss.

**Comment by hjk22** [comment]
Other users reported this issue too and it seems to be related to the search for elite units.

**Comment by jmangs** [comment]
Probably due to the color range of the boss fleet flagship being in the same range as the elites. I think Monarch had this issue in the past for me. Easiest solution may be to look for the ammo counter and remove the match. Until then you'll have to adjust the flagship or turn off elite searching.
